### PR TITLE
added riscv/rv64g support

### PR DESCRIPTION
**Pull request by ct-clmsn**
added riscv support (rv64g) and included performance csv files for the sifive hifive unmatched.

### CODE REVIEW

**Comment by ct-clmsn** [comment]
@diehlpk some modifications were made to the benchmark script specifically to support the sifive processor's core count (4); hopefully `srun --cpus-per-task=4 --ntasks-per-node=1 --ntasks-per-core=1` is an appropriate configuration for the slurm runs.

**Comment by ct-clmsn** [comment]
@diehlpk the codacy analyzer doesn't like `benchmark.sh`

**Comment by diehlpk** [comment]
@ct-clmsn I will have a look tomorrow.

**Comment by diehlpk** [comment]
I will plot the data tomorrow and add them to the paper. 

Thanks for providing the data.

**Comment by diehlpk** [comment]
I added the plots to the paper and everything looks good.

**Pull request merged**
